//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogWebUI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogWebUIEntities : DbContext
    {
        public BlogWebUIEntities()
            : base("name=BlogWebUIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAdminRol> tblAdminRol { get; set; }
        public virtual DbSet<tblEtiket> tblEtiket { get; set; }
        public virtual DbSet<tblGonderi> tblGonderi { get; set; }
        public virtual DbSet<tblKategori> tblKategori { get; set; }
        public virtual DbSet<tblKullanici> tblKullanici { get; set; }
        public virtual DbSet<tblNormalRol> tblNormalRol { get; set; }
        public virtual DbSet<tblYorum> tblYorum { get; set; }
    }
}
