//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogWebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEtiket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEtiket()
        {
            this.tblGonderi = new HashSet<tblGonderi>();
        }
    
        public int etiketId { get; set; }
        public string etiketBaslik { get; set; }
        public string etiketIcerik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGonderi> tblGonderi { get; set; }
    }
}
