//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogWebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGonderi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGonderi()
        {
            this.tblYorum = new HashSet<tblYorum>();
        }
    
        public int gonderiId { get; set; }
        public Nullable<int> gonderiKullaniciId { get; set; }
        public Nullable<int> gonderiKullaniciUyelikRolId { get; set; }
        public Nullable<int> gonderiKullaniciAdminId { get; set; }
        public Nullable<int> gonderiKategoriId { get; set; }
        public string gonderiBaslik { get; set; }
        public Nullable<int> gonderiEtiketId { get; set; }
        public string gonderiOzet { get; set; }
        public Nullable<int> gonderiYayinlanma { get; set; }
        public Nullable<System.DateTime> gonderiOlusturulmaTarihi { get; set; }
        public Nullable<System.DateTime> gonderiGuncellenmeTarihi { get; set; }
        public Nullable<System.DateTime> gonderiYayinlanmaTarihi { get; set; }
        public string gonderiIcerik { get; set; }
    
        public virtual tblAdminRol tblAdminRol { get; set; }
        public virtual tblEtiket tblEtiket { get; set; }
        public virtual tblKategori tblKategori { get; set; }
        public virtual tblKullanici tblKullanici { get; set; }
        public virtual tblNormalRol tblNormalRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblYorum> tblYorum { get; set; }
    }
}
