//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogWebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKullanici()
        {
            this.tblGonderi = new HashSet<tblGonderi>();
        }
    
        public int kullaniciId { get; set; }
        public Nullable<int> kullaniciUyelikRolId { get; set; }
        public Nullable<int> kullaniciAdminId { get; set; }
        public string kullaniciAdSoyad { get; set; }
        public string kullaniciTelNo { get; set; }
        public string kullaniciEmail { get; set; }
        public string kullaniciInstagram { get; set; }
        public string kullaniciTwitter { get; set; }
        public string kullaniciGitHub { get; set; }
        public string kullaniciLinkedin { get; set; }
        public string kullaniciTakmaAd { get; set; }
        public string kullaniciSifreHash { get; set; }
        public Nullable<System.DateTime> kullaniciKayitOlmaTarihi { get; set; }
        public Nullable<System.DateTime> kullaniciSonGirisTarihi { get; set; }
        public string kullaniciGiris { get; set; }
        public string kullaniciProfilYazisi { get; set; }
    
        public virtual tblAdminRol tblAdminRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGonderi> tblGonderi { get; set; }
        public virtual tblNormalRol tblNormalRol { get; set; }
    }
}
