//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogWebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblYorum
    {
        public int yorumId { get; set; }
        public Nullable<int> yorumGonderiId { get; set; }
        public Nullable<int> yorumKullaniciRolId { get; set; }
        public Nullable<int> yorumKullaniciAdminId { get; set; }
        public string yorumBaslik { get; set; }
        public Nullable<int> yorumYayinlanma { get; set; }
        public Nullable<System.DateTime> yorumOlusturulmaTarihi { get; set; }
        public Nullable<System.DateTime> yorumYapilmaTarihi { get; set; }
        public string yorumIcerik { get; set; }
    
        public virtual tblAdminRol tblAdminRol { get; set; }
        public virtual tblGonderi tblGonderi { get; set; }
        public virtual tblNormalRol tblNormalRol { get; set; }
    }
}
